"""posts

Revision ID: 65200d296898
Revises: e7c0d5b22728
Create Date: 2023-11-19 22:36:05.894938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65200d296898'
down_revision = 'e7c0d5b22728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
